# Generated by Django 2.1.3 on 2018-12-16 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_logo',
            field=models.CharField(max_length=250),
        ),
    ]
