# Generated by Django 2.1.3 on 2018-12-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_auto_20181216_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='distance',
            field=models.IntegerField(default=10),
        ),
    ]
